niche/generate-pkgdev-docs: significantly tidy up
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/niche/generate-pkgdev-docs b/niche/generate-pkgdev-docs
--- a/niche/generate-pkgdev-docs
+++ b/niche/generate-pkgdev-docs
@@ -1,22 +1,36 @@
 #!/usr/bin/env bash
 . /lib/gentoo/functions.sh
-. /usr/share/iwdevtools/atomf.bashlib
+. "$(pkg-config iwdevtools --variable=atomf)" || exit
 
-ebuild=${1}
-version=$(atomf "%V" "${ebuild/.ebuild}")
-pf=$(atomf "%n%v%r" "${ebuild/.ebuild}")
+atomset ${1}
 
-PKGDEV_DOCS_PREBUILT=0 USE=doc ebuild ${1} clean compile
+export PKGDEV_DOCS_PREBUILT=0
+
+# We don't want to compress the man pages ourselves
+export PORTAGE_COMPRESS_EXCLUDE_SUFFIXES=".*"
+export PORTAGE_TMPDIR=${PORTAGE_TMPDIR:-/tmp/sam-gentoo-scripts/${0##*/}}
+export XZ_DEFAULTS="-9 -T 0"
+
+sudo USE=doc emerge -q1o =${PF}
+
+# We need this to flush out a previous doc entry from a failed attempt
+USE=doc ebuild ${1} manifest
+USE=doc ebuild ${1} clean compile install
+
+D="${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/image
+WORKDIR="${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/work
+# Borrowed from mgorny-dev-tools' pkgdiff
+S=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/temp/environment)
 
 dir=$(mktemp -d)
-mkdir "${dir}"/pkgdev-${version}-docs
+mkdir "${dir}"/${P}-docs
 
-ebegin "Copying docs to ${dir}/pkgdev-${version}-docs"
-cp -ra /var/tmp/portage/dev-util/${pf}/work/pkgdev-*/man "${dir}"/pkgdev-${version}-docs/
+ebegin "Copying docs to ${dir}/${P}-docs"
+cp -r "${S}"/man "${dir}"/${P}-docs/
 eend $? || exit 1
 
 ebegin "Creating tarball"
-tar -caf "${dir}"/pkgdev-${version}-docs.tar.xz -C "${dir}" pkgdev-${version}-docs/
-eend $? || exit 1
+tar -caf "${dir}"/${P}-docs.tar.xz -C "${dir}" ${P}-docs/
+eend ${?} || exit 1
 
-einfo "Tarball at ${dir}/pkgdev-${version}-docs.tar.xz"
+einfo "Tarball at ${dir}/${P}-docs.tar.xz"
