niche: add error handling
Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/niche/generate-pkgdev-docs b/niche/generate-pkgdev-docs
--- a/niche/generate-pkgdev-docs
+++ b/niche/generate-pkgdev-docs
@@ -5,7 +5,7 @@ else
 	SCRIPT_DIR=./
 fi
 
-. ${SCRIPT_DIR}/generate-docs.bashlib
+. ${SCRIPT_DIR}/generate-docs.bashlib || { echo "Failed to source generate-docs.bashlib!" ; exit 1 ; }
 
 export PKGDEV_DOCS_PREBUILT=0
 
