maint/bump-go: use iwdevtools for atomset
Cleans things up substantially and avoids us repeating ourselves.

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/maint/bump-go b/maint/bump-go
--- a/maint/bump-go
+++ b/maint/bump-go
@@ -1,8 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # TODO: could add guessed subdir into S in ebuild?
 # TODO: handle licensing
-# TODO: handle where a vendor dir alraedy exists
-. /lib/gentoo/functions.sh
+# TODO: handle where a vendor dir already exists
+. /lib/gentoo/functions.sh || { echo "Could not find gentoo-functions' functions.sh!" ; exit 1; }
+. "$(pkg-config iwdevtools --variable=atomf)" || { eerror "Could not find iwdevtools' atomf library! Emerge app-portage/iwdevtools?" ; exit 1; }
 
 if [[ ${BASH_SOURCE} = */* ]]; then
 	SCRIPT_DIR=${BASH_SOURCE%/*}/
@@ -16,11 +17,10 @@ ORIGINAL_PWD=$(pwd)
 REPRODUCABLE_TAR_ARGS="--mtime="${SOURCE_DATE_EPOCH:-1970-01-01}" --sort=name --owner=portage --group=portage"
 
 ${SCRIPT_DIR}/bump-generic $@ || exit 1
-
 cd ${1} || exit 1
+atomset "${1}-${2}"
 
-pn=$(pwd | rev | cut -d/ -f1 | rev)
-ebuild=${pn}-${2}.ebuild
+ebuild=${P}.ebuild
 
 # Now do the Go-specific bits.
 #
@@ -44,20 +44,28 @@ if grep -q "EGO_SUM" ${ebuild} ; then
 fi
 
 # 2. Fetch!
-einfo "Fetching ${1}-${2}"
+einfo "Fetching ${P}"
 ebuild ${ebuild} manifest || exit 1
 
 # 3. Unpack then fetch Go deps
-einfo "Unpacking ${1}-${2}"
+einfo "Unpacking ${P}"
 
 # (We want to own this place)
-WORKDIR=$(mktemp -d || exit 1)
-PORTAGE_USERNAME="$(whoami)" PORTAGE_WORKDIR_MODE="775" PORTAGE_TMPDIR="${WORKDIR}" ebuild ${ebuild} clean unpack || exit 1
+export PORTAGE_TMPDIR="$(mktemp -d)"
+export PORTAGE_USERNAME="$(whoami)"
+export PORTAGE_WORKDIR_MODE="775"
+ebuild ${ebuild} clean unpack || exit 1
+
+# We need to export these for use in the subshells :(
+export D="${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/image
+export WORKDIR="${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/work
+# Borrowed from mgorny-dev-tools' pkgdiff
+export S=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${CATEGORY}/${PF}/temp/environment)
 
 cmd='GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw'
 ebegin "Running '${cmd}'"
 (
-    cd "${WORKDIR}"/portage/${1}-${2}/work/${pn}-${2}/ || exit 1
+    cd "${S}" || exit 1
 
     if [[ ! -f go.mod ]] ; then
         ewarn "No go.mod in $(pwd)!"
@@ -77,18 +85,18 @@ ebegin "Running '${cmd}'"
 
 ebegin "Creating tarball"
 (
-    cd "${WORKDIR}"/portage/${1}-${2}/work/${pn}-${2}/ || exit 1
+    cd "${S}" || exit 1
 
     # Find the (sub)dir we used earlier, even if it was a subdir we guessed
     cd $(find . -maxdepth 2 -type d -name '*go-mod*' -print -quit || exit 1)/.. || exit 1
 
-    tar ${REPRODUCABLE_TAR_ARGS} -acf ${pn}-${2}-deps.tar.xz go-mod || exit 1
+    tar ${REPRODUCABLE_TAR_ARGS} -acf ${P}-deps.tar.xz go-mod || exit 1
 
-    mv ${pn}-${2}-deps.tar.xz $(portageq distdir)/ || exit 1
+    mv ${P}-deps.tar.xz $(portageq distdir)/ || exit 1
 ) || { eend $? ; exit 1; }
 
 # 4. Undo the sed we did earlier to the ebuild
-cd ${ORIGINAL_PWD}/${1} || exit 1
+cd ${ORIGINAL_PWD}/${CATEGORY}/${PN} || exit 1
 einfo "Unsedding deps line in ebuild"
 sed -i -e "/^#SRC_URI.*deps/ s/^#//" ${ebuild} || exit 1
 
@@ -96,5 +104,4 @@ einfo "Generating manifest"
 ebuild ${ebuild} clean manifest || exit 1
 
 einfo "All done."
-einfo "Dep tarball now at: $(portageq distdir)/${pn}-${2}-deps.tar.xz!"
-
+einfo "Dep tarball now at: $(portageq distdir)/${P}-deps.tar.xz!"
