maint: use tabs for indentation, per Gentoo ebuild style
This is all ebuild tooling, so...

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/maint/bump-go b/maint/bump-go
--- a/maint/bump-go
+++ b/maint/bump-go
@@ -30,11 +30,11 @@ sed -i -e "/^SRC_URI.*deps/ s/^/#/" ${ebuild} || exit 1
 
 einfo "Sedding out 'EGO_SUM' lines if they exist"
 if grep -q "EGO_SUM" ${ebuild} ; then
-        if grep -qe 'EGO_SUM".*"' ${ebuild} ; then
-                sed -i -e '/EGO_SUM/d' ${ebuild} || exit 1
-        else
-                sed -i -e '/EGO_SUM=(/,/)/d' ${ebuild} || exit 1
-        fi
+	if grep -qe 'EGO_SUM".*"' ${ebuild} ; then
+		sed -i -e '/EGO_SUM/d' ${ebuild} || exit 1
+	else
+		sed -i -e '/EGO_SUM=(/,/)/d' ${ebuild} || exit 1
+	fi
 
 	sed -i -e '/EGO_SUM_SRC_URI/d' ${ebuild} || die
 	sed -i -e '/go-module_set_globals/d' ${ebuild} || die
@@ -65,34 +65,34 @@ export S=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${C
 cmd='GOMODCACHE="${PWD}"/go-mod go mod download -modcacherw'
 ebegin "Running '${cmd}'"
 (
-    cd "${S}" || exit 1
+	cd "${S}" || exit 1
 
-    if [[ ! -f go.mod ]] ; then
-        ewarn "No go.mod in $(pwd)!"
-        ewarn "Guessing first top-level subdir with go.mod?"
-        dirs=$(find . -maxdepth 1 -type d -print)
+	if [[ ! -f go.mod ]] ; then
+		ewarn "No go.mod in $(pwd)!"
+		ewarn "Guessing first top-level subdir with go.mod?"
+		dirs=$(find . -maxdepth 1 -type d -print)
 
-        for dir in ${dirs[@]} ; do
-            if [[ -f ${dir}/go.mod ]] ; then
-                einfo "Entering ${dir} which contains a go.mod file"
-                cd ${dir} || exit 1
-            fi
-        done || { eerror "Could not find any go.mod in top-level subdirs either!" ; exit 1; }
-    fi
+		for dir in ${dirs[@]} ; do
+			if [[ -f ${dir}/go.mod ]] ; then
+				einfo "Entering ${dir} which contains a go.mod file"
+				cd ${dir} || exit 1
+			fi
+		done || { eerror "Could not find any go.mod in top-level subdirs either!" ; exit 1; }
+	fi
 
-    eval "${cmd}" || exit 1
+	eval "${cmd}" || exit 1
 ) || { eend $? ; exit 1; }
 
 ebegin "Creating tarball"
 (
-    cd "${S}" || exit 1
+	cd "${S}" || exit 1
 
-    # Find the (sub)dir we used earlier, even if it was a subdir we guessed
-    cd $(find . -maxdepth 2 -type d -name '*go-mod*' -print -quit || exit 1)/.. || exit 1
+	# Find the (sub)dir we used earlier, even if it was a subdir we guessed
+	cd $(find . -maxdepth 2 -type d -name '*go-mod*' -print -quit || exit 1)/.. || exit 1
 
-    tar ${REPRODUCIBLE_TAR_ARGS} -acf ${P}-deps.tar.xz go-mod || exit 1
+	tar ${REPRODUCIBLE_TAR_ARGS} -acf ${P}-deps.tar.xz go-mod || exit 1
 
-    mv ${P}-deps.tar.xz $(portageq distdir)/ || exit 1
+	mv ${P}-deps.tar.xz $(portageq distdir)/ || exit 1
 ) || { eend $? ; exit 1; }
 
 # 4. Undo the sed we did earlier to the ebuild
diff --git a/maint/bump-rust b/maint/bump-rust
--- a/maint/bump-rust
+++ b/maint/bump-rust
@@ -5,9 +5,9 @@
 . "$(pkg-config iwdevtools --variable=atomf)" || { eerror "Could not find iwdevtools' atomf library! Emerge app-portage/iwdevtools?" ; exit 1; }
 
 if [[ ${BASH_SOURCE} == */* ]]; then
-        SCRIPT_DIR=${BASH_SOURCE%/*}/
+	SCRIPT_DIR=${BASH_SOURCE%/*}/
 else
-        SCRIPT_DIR=./
+	SCRIPT_DIR=./
 fi
 
 ORIGINAL_PWD=$(pwd)
@@ -56,32 +56,32 @@ export S=$(sed -nr 's/^declare -x S="(.*)"/\1/p' "${PORTAGE_TMPDIR}"/portage/${C
 cmd='CARGO_HOME="${PWD}"/cargo-tmp cargo fetch'
 ebegin "Running '${cmd}'"
 (
-    cd "${S}" || exit 1
+	cd "${S}" || exit 1
 
-    if [[ ! -f Cargo.toml ]] ; then
-        ewarn "No Cargo.toml in $(pwd)!"
-        ewarn "Guessing first top-level subdir with Cargo.toml?"
-        dirs=$(find . -maxdepth 1 -type d -print)
+	if [[ ! -f Cargo.toml ]] ; then
+		ewarn "No Cargo.toml in $(pwd)!"
+		ewarn "Guessing first top-level subdir with Cargo.toml?"
+		dirs=$(find . -maxdepth 1 -type d -print)
 
-        for dir in ${dirs[@]} ; do
-            if [[ -f ${dir}/Cargo.toml ]] ; then
-                einfo "Entering ${dir} which contains a Cargo.toml file"
-                cd ${dir} || exit 1
-            fi
-        done || { eerror "Could not find any Cargo.toml in top-level subdirs either!" ; exit 1; }
-    fi
+		for dir in ${dirs[@]} ; do
+			if [[ -f ${dir}/Cargo.toml ]] ; then
+				einfo "Entering ${dir} which contains a Cargo.toml file"
+				cd ${dir} || exit 1
+			fi
+		done || { eerror "Could not find any Cargo.toml in top-level subdirs either!" ; exit 1; }
+	fi
 
-    eval "${cmd}" || exit 1
+	eval "${cmd}" || exit 1
 ) || { eend $? ; exit 1; }
 
 ebegin "Creating CRATES variable"
 (
-    cd "${S}" || exit 1
+	cd "${S}" || exit 1
 
-    # TODO: nullglob?
-    crates=$(ls -1 cargo-tmp/registry/src/*)
+	# TODO: nullglob?
+	crates=$(ls -1 cargo-tmp/registry/src/*)
 
-    echo ${crates} > "${WORKDIR}"/crates-list
+	echo ${crates} > "${WORKDIR}"/crates-list
 ) || { eend $? ; exit 1; }
 
 # Add CRATES back
