maint/bump-generic: use iwdevtools for atomset
Cleans things up substantially and avoids us repeating ourselves.

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/maint/bump-generic b/maint/bump-generic
--- a/maint/bump-generic
+++ b/maint/bump-generic
@@ -1,6 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # TODO: merge this with ebump somehow?
-. /lib/gentoo/functions.sh
+. /lib/gentoo/functions.sh || { echo "Could not find gentoo-functions' functions.sh!" ; exit 1; }
+. "$(pkg-config iwdevtools --variable=atomf)" || { eerror "Could not find iwdevtools' atomf library! Emerge app-portage/iwdevtools?" ; exit 1; }
+
+template_pkg=net-dns/dnsx
 
 get_last_version() {
     local cpn=${1}
@@ -13,21 +16,18 @@ get_last_version() {
         last_version_cpv=$(portageq best_visible "${EROOT:-/}" "<${cpn}-${ver}")
     fi
 
-    last_version_p=$(qatom -F "%{PF}" ${last_version_cpv})
-
-    echo ${last_version_p}
+    last_version_pf=$(atomf "%f" ${last_version_cpv})
+    echo ${last_version_pf}
 }
 
-pkg=${1}
-ver=${2}
-template_pkg=net-dns/dnsx
+atomset "${1}-${2}"
 
-if [[ -z ${pkg} ]] ; then
+if [[ -z ${CATEGORY}/${PN} ]] ; then
     eerror "No package given!"
     exit 1
 fi
 
-if [[ -z ${ver} ]] ; then
+if [[ -z ${PV} ]] ; then
     eerror "No version given!"
     exit 1
 fi
@@ -37,33 +37,31 @@ if [[ ! -d profiles/ ]] ; then
     exit 1
 fi
 
-pn=$(echo ${pkg} | cut -d/ -f2)
-
-einfo "Bumping ${pkg} to ${ver}"
+einfo "Bumping ${CATEGORY}/${PN} to ${PV}"
 
 # Is it a new package?
-if [[ ! -d ${pkg} ]] ; then
-    einfo "${pkg} does not yet exist, using ${template_pkg} as template"
+if [[ ! -d ${CATEGORY}/${PN} ]] ; then
+    einfo "${CATEGORY}/${PN} does not yet exist, using ${template_pkg} as template"
 
-    mkdir -p ${pkg} || exit 1
-    cd ${pkg} || exit 1
+    mkdir -p ${CATEGORY}/${PN} || exit 1
+    cd ${CATEGORY}/${PN} || exit 1
 
     last_version_p=$(get_last_version ${template_pkg})
 
-    cp ../../${template_pkg}/${last_version_p}.ebuild ${pn}-${ver}.ebuild || exit 1
+    cp ../../${template_pkg}/${last_version_p}.ebuild ${P}.ebuild || exit 1
 
-    einfo "Created ${pkg}/${pn}-${ver}.ebuild from ${template_pkg}/${last_version_p}.ebuild. Please edit as needed."
-elif [[ -f ${pkg}/${pn}-${ver}.ebuild ]] ; then
+    einfo "Created ${CATEGORY}/${PN}/${P}.ebuild from ${template_pkg}/${last_version_p}.ebuild. Please edit as needed."
+elif [[ -f ${CATEGORY}/${PN}/${P}.ebuild ]] ; then
     # Does this version already exist?
-    ewarn "${pn}-${ver}.ebuild already exists! Skipping creation."
+    ewarn "${P}.ebuild already exists! Skipping creation."
 else
-    mkdir -p ${pkg} || exit 1
-    cd ${pkg} || exit 1
+    mkdir -p ${CATEGORY}/${PN} || exit 1
+    cd ${CATEGORY}/${PN} || exit 1
 
     # Already exists
-    last_version_p=$(get_last_version ${pkg} ${ver})
+    last_version_p=$(get_last_version ${CATEGORY}/${PN} ${PV})
 
-    cp ${last_version_p}.ebuild ${pn}-${ver}.ebuild || exit 1
+    cp ${last_version_p}.ebuild ${P}.ebuild || exit 1
 
-    einfo "Created ${pkg}/${pn}-${ver}.ebuild. Please edit as needed."
+    einfo "Created ${CATEGORY}/${PN}/${P}.ebuild. Please edit as needed."
 fi
