maint/bump-generic: more error handling
Note that this means we don't have to do some
bits in bump-go, bump-rust.

Signed-off-by: Sam James <sam@gentoo.org>

diff --git a/maint/bump-generic b/maint/bump-generic
--- a/maint/bump-generic
+++ b/maint/bump-generic
@@ -20,12 +20,7 @@ get_last_version() {
     echo ${last_version_pf}
 }
 
-atomset "${1}-${2}"
-
-if [[ -z ${CATEGORY}/${PN} ]] ; then
-    eerror "No package given!"
-    exit 1
-fi
+atomset "${1}-${2}" || { eerror "atomset failed! Insufficient arguments? We need: ${0##*/} <CATEGORY/PN> <PV>" ; exit 1; }
 
 if [[ -z ${PV} ]] ; then
     eerror "No version given!"
